name: Build

on:
  workflow_dispatch:
jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - java: '17'
          expander_leg: ubuntu-latest--x64
      fail-fast: false

    name: Build with Java ${{ matrix.java }} in Ubuntu [${{ matrix.expander_leg 
      }}]
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v6
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        java-package: jdk
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B -ff -ntp clean install

    - name: Publish Code Coverage
      if: github.ref == 'refs/heads/main' && matrix.java == '17'
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella

    timeout-minutes: 150
